language: node_js
node_js:
  - "node"
cache: yarn
env:
  global:
    # SAUCE_USERNAME
    - secure: "Cw2tEVy8tJqls5d+iLjrCbSkfF+tTeLP97p2wI/9lMdSdZZRalVo+SA88t0Y4ww+0bnBrerqeGOqvDLO5rtskQ+9qXvhKtY1AU3qBmQjwCCFuhVzb4b2ArWNcLrK2MrDYnuEosI9s7akHDvD/3eUZwMv6PmPLdI4QjkQi2U9SQDtqngLBwO2+qp8gE8lcsQNtCQT0Tww6YQnbgRnQEJ6rbFAaEhs2CzDG1eGarCun0VkKFpE9lHBLfHytsccP5F+rOFiSx344h5SJzQM00pN9xySsqJnTq2nmyYaOUqXAYzIlTzFYhDsSEGLgFoZDv5uDO4qhEX86xYAcgP4iT/1USo/5bD1xzgKzwbvKUw8xS74iWWjVVVeexBMIOkFnNhM0ksatwO9LtQPAHIOWRHEO9/OMtsMbitzHTQHO8I3aV/xvTd+G9Ob8UIb/KcZj03xhH2zmPERoB74u6RLDU9HHoPWqqLg2olgLMbxtZuEUNZeNpA42wik1e/dGKylK0elBwtKDwk/nVe0yTuY+GmjSh247SL7U3rihQVl3fIILoAIXH6vTvWt87BOauudFD/wrxeDB99XdNidlOpvQCXA8nlHns8NEZ3JXe62wERRoE78ksVay7qAVFRqwZQHBkH2393Dxl1Qkv2gUo0xIDpwLtP1SicuI/EGrju9fCTk6mU="
    # SAUCE_ACCESS_KEY
    - secure: "B3ZilHiNjOHxNvO/813QFTkWTjmkMiEKgnpdECG+XKR0+D10RnmIFoWj/h9H4ae5ky9UdNH7s9Wh1mu7C6mkBNn0w6bLdnT+dBuMwuJ7x09u+B/4MQ6BhHyVJZLp0cJatfYFMrMEJO2D5SnvtdSJfDEgSUagWAokdJCGNvg4hdj+A28hmXZIVyojhb41B5KKVZmxgX94p16SONjwzkejfkJm87L0MiXMtAb/njXhxeAJGvJGojBUXK5k9xFy1beQn+lhUki43X/O8Q73VNAG7WKQb54VOfOclfrd5xCOBNdnDm5ZzzHt8fOD3gU1fZXuFAMlqnmuNulSxPFDGTYWlrJ9JqbhzX+o2a5TKaPaXjCnjCnL90rL/0ld875NYm88za0Y8NFBdYVDHGLtrKPYsfqjWaofIMnVYo/ieVVyGRFj5fj2m8XrK0yCPF/UfUELuXJdw8hJI7/Z/WKs+wS3w6SqEFw05ylyEZmiMj4AleLyb/a88TqM7DtruBlFPJoYxw1aevtrVpUuJLrPi69woDflWtKfoZxBcRiZyPaf+of7MOVlQq87gyiPTOhiNCMf+9Oy8MXZSK5lsRCy1AS7rkWnSTn5YHrkly+EAuajOe4yr9ekOGAmc3IDfR86z7ERNx5JoLi1koA3NuiAyu1reYloJgjaByc+Y+zqdZq9On0="
script:
  - npm run bower
  - npm run test
  - npm run test:es5
